export class ComunicacionAlternativaClass{
  constructor(
    public nombre?:string,
    public imagen1?:string,
    public imagen2?:string,
    public imagen3?:string,
    public imagen4?:string,
    public imagen5?:string,
    public imagen6?:string,
    public imagen7?:string,
    public imagen8?:string,
    public imagen9?:string,
    public imagen10?:string,
    public imagen11?:string,
    public imagen12?:string,
    public imagen13?:string,
    public imagen14?:string,
    public imagen15?:string,
    public imagen16?:string,
    public imagen17?:string,
    public imagen18?:string,
    public imagen19?:string,
    public imagen20?:string,
    public imagen21?:string,
    public imagen22?:string,
    public imagen23?:string,
    public imagen24?:string,
    public imagen25?:string,
    public imagen26?:string,
    public idTerapeuta?:string,
    public createdAt?:Date,
    public updatedAt?:Date,
    public id?:string,
    public editar?:boolean
  ){}
}
